{% set name = "finam" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finam-{{ version }}.tar.gz
  sha256: 6adc4b3fb0bafd7115be21cc3fd90a14295e4b9602a4ff0e1627be8210924533
  patches:
    - skip_c_log_test_win.patch  # [win]

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - numpy >=1.14.5
    - scipy >=1.9.0
    - pyevtk >=1.1.1
    - pint >=0.20.0
    - pyproj >=3.4
    - pandas >=1.3
    - opensimplex >=0.4

test:
  imports:
    - finam
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  summary: FINAM is not a model.
  home: https://finam.pages.ufz.de
  doc_url: https://finam.pages.ufz.de/finam
  dev_url: https://git.ufz.de/FINAM/finam
  description: |
    FINAM is an open-source component-based model coupling framework for environmental models.
    It aims at enabling bi-directional online couplings of models for different compartments like
    geo-, hydro-, pedo- and biosphere.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSE.md
    - AUTHORS.md

extra:
  recipe-maintainers:
    - MuellerSeb
    - mlange-42
    - finam-admin
